name: bs-build
on:
  push:
    branches: [master]
jobs:
  build-for-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          clean: false
          ref: gh-pages
      - name: Prepare build tree
        run: |
          git config user.name  github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git merge --allow-unrelated-histories -s recursive -X theirs $GITHUB_SHA
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: |
          npx bsb -make-world
          npx webpack -c webpack.config.js -o docs
      - name: Publish changes
        run: |
          git add docs
          git commit -m "
          Update gh-pages [action $GITHUB_RUN_ID]

          ------------------------ 8< ------------------------
          Built from: $GITHUB_SHA
          " --amend && git push || true
