name: bs-build
on:
  push:
    branches: [master]
jobs:
  build-for-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          clean: false
          ref: gh-pages
      - name: Prepare build tree
        run: |
          git config user.name  $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git config committer.name  github-actions[bot]
          git config committer.email 41898282+github-actions[bot]@users.noreply.github.com

          git merge --allow-unrelated-histories -s recursive -X theirs $GITHUB_SHA
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: |
          npx bsb -make-world
          npx webpack -c webpack.config.js -o docs
      - name: Publish changes
        run: |
          git add docs
          git commit -m "Update page content

          ------------
          Github Action run id: $GITHUB_RUN_ID
          Built from: $GITHUB_SHA
          " --amend && git push || true
